In [1]:
import tensorflow as tf
import tensorflow_data_validation as tfdv
import tensorflow_transform as tft
import apache_beam as beam
import pandas as pd

print('Tf version: ', tf.__version__)
print('TFDV version: ', tfdv.__version__)
print('TFT version: ', tft.__version__)
print('Apache beam version: ', beam.__version__)
print('Pandas version: ', pd.__version__)

#tf.compat.v1.disable_eager_execution()



Tf version:  2.17.0
TFDV version:  1.14.0
TFT version:  1.14.0
Apache beam version:  2.65.0
Pandas version:  1.5.3


In [4]:
raw_features = {
    'Company':          tf.constant([b'Lenovo']),
    'TypeName':         tf.constant([b'Ultrabook']),
    'Inches':           tf.constant([15.6]),
    'ScreenResolution': tf.constant([b'1920x1080']),
    'Cpu':              tf.constant([b'Intel Core i7']),
    'Ram':              tf.constant([b'16.0']),
    'Memory':           tf.constant([b'512.0']),
    'Gpu':              tf.constant([b'NVIDIA GTX 1650']),
    'OpSys':            tf.constant([b'Windows 10']),
    'Weight':           tf.constant([b'2.5']),
    'Price':            tf.constant([999.99]),
}


In [5]:
tft_output = tft.TFTransformOutput('train/transform_fn')
transformed_features = tft_output.transform_raw_features(raw_features)
print(transformed_features)

INFO:tensorflow:struct2tensor is not available.
INFO:tensorflow:tensorflow_decision_forests is not available.
INFO:tensorflow:tensorflow_text is not available.
{'scaled_weight': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.4132859], dtype=float32)>, 'scaled_height': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.67172724], dtype=float32)>, 'cpu_family_xf': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([3], dtype=int64)>, 'scaled_ram': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([13.474522], dtype=float32)>, 'scaled_price': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.8383343], dtype=float32)>, 'cpu_brand_xf': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([0], dtype=int64)>, 'opsys_xf': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([0], dtype=int64)>, 'typename_xf': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1], dtype=int64)>, 'scaled_width': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.6720362], dtype=float32)>, 'gpu_model_xf'